
#Teszt
spring:
  datasource:
    platform: oracle
    url: jdbc:oracle:thin:@//172.17.9.13:8882/nautest.econsult.hu
#    url: jdbc:oracle:thin:@//172.17.9.13:8880/naudemo.econsult.hu
    username: NAUTICOM
    password: NAUTICOM
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      minimum-idle: 20
      maximum-pool-size: 100
      connection-init-sql: begin naudba.p_set_client_info('IS4-DEMO'); end;
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    properties:
      hibernate:
        ddl-auto: none
        show_sql: true
        format_sql: true
        proc.param_null_passing: true
logging:
  level:
    org:
      hibernate:
        type: TRACE
#        SQL: INFO


#ELES
#spring:
#  datasource:
#    platform: oracle
#    url: jdbc:oracle:thin:@172.17.1.3:8880:nauticom
#    username: NAUTICOM
#    password: NAUTICOM
#    driver-class-name: oracle.jdbc.OracleDriver
#  jpa:
#    database-platform: org.hibernate.dialect.Oracle10gDialect
#    properties:
#      hibernate:
#        ddl-auto: none
#        show_sql: true
#        format_sql: true
#        proc.param_null_passing: true
#logging:
#  level:
#    org:
#      hibernate:
#        type: TRACE
#        SQL: DEBUG